### ISSUE TITLE
Broken demos

### ISSUE THREAD

**Issue by Happy-Ferret** [magcius/xplain#10]
After recently rediscovering this project (been looking for this for a really long time, after first trying the demos over a year ago), I was keen to try out some of the demos. 

Unfortunately, some of them appear to be broken. 

[THE INTANGIBLE IMAGE](https://magcius.github.io/xplain/article/composite.html) won't let me drag the top kitten image, contrary to what the text implies 

```
Go on, drag the top kitten around, and you'll notice it wobbling in real-time.
```

[WINDOWS OF ALL SHAPES AND SIZES](https://magcius.github.io/xplain/article/x-basics.html) meanwhile doesn't display the circular window that is supposed to be there (and used to be there in the past). It does, in fact, not display anything but the root window and the inspector button.

**Comment by magcius** [comment]
Gah, sorry about that! Should be fixed now.
