### ISSUE TITLE
Cannot get math

### ISSUE THREAD

**Issue by valsoray17** [magcius/xplain#11]
Is it me or is there something wrong with the math on this [line](https://github.com/magcius/xplain/blob/6a53dc9b9778c6edf17ba560034aa8382c909184/article/regions.html#L376)

(16*4+8) bytes = 132 bytes

Anyway, the series is awesome! Thanks for the great explanation!

**Comment by magcius** [comment]
I think when I did the calculation, I did (16*8+4), which is wrong. Thanks for spotting it! I'll see about fixing it soon.
