### ISSUE TITLE
Duplicated words

### ISSUE THREAD

**Issue by Estevo-Aleixo** [magcius/xplain#2]
x-basics.html#L323 This is how Windows works, and why you see the the repeated "IE6 crashed" window when explorer.exe
s/the the/the/
window-tree.html#L157 to construct a bunch of X11 windows as if they were widgets and get a nice, reflowing form form field.
s/form form/form/

These can be found in the future by "w3m -dump somefile.html |  tr ' ,.?' '\n' | uniq -c | grep -v '^[ ]+1 ' | grep -i [a-z]"
there is probably a better way with awk (and I would love to see it).

**Comment by Estevo-Aleixo** [comment]
gawk info page has a dupword example http://www.gnu.org/software/gawk/manual/gawk.html#Dupword-Program

**Comment by magcius** [comment]
Thanks!
