### ISSUE TITLE
A thank you and a request.

### ISSUE THREAD

**Issue by lgieron** [magcius/xplain#22]
I wanted to thank you for your excellent technical writing on the X Window System. If only all content available on the net was of this quality...
Since you asked for requests that may provide you with some motivation to continue writing - I'd like to learn more about the MIT-SHM extension. I'm interested in performant drawing to bitmaps, and it seems like the best solution that does not involve a GPU.

Thanks again,
Łukasz

**Comment by magcius** [comment]
Thank you! I think you might enjoy my next planned article, then.

**Comment by magcius** [comment]
Very early preview: http://magcius.github.io/xplain/article/rast1.html
