### ISSUE TITLE
Wrong extents for subtract operation?

### ISSUE THREAD

**Issue by krlospelaez** [magcius/xplain#23]
When doing a subtract between 2 regions I expect the extents were src1.extents but instead I'm getting the union between src1 and src2 extents.

I'm not sure if that's intended but this line (https://github.com/magcius/xplain/blob/gh-pages/src/region.js#L319) is never executed in any of the operations. I thought it was executed when subtract op.

Thanks for this great explanation 👍

**Comment by magcius** [comment]
Fixed with https://github.com/magcius/xplain/commit/adcd66bcaf842f3e572074bd81023f8b9c8757e8

Genuine tricky typo bug, thank you for the report!
