### ISSUE TITLE
Chromium link in regions.html is broken

### ISSUE THREAD

**Issue by zmodem** [magcius/xplain#27]
The link in "Some applications, like Chromium, actually still do this in their own window decorations." doesn't seem to work. The code is still there, but the code search interface doesn't seem to like the "rcl" parameter.

Maybe a link to the git repo is more stable: https://chromium.googlesource.com/chromium/src/+/d7d447a09a95eb7ad399eb8512f677a66e127d69/ui/views/window/window_shape.cc#12

**Comment by magcius** [comment]
the wonder of the modern web

**Comment by magcius** [comment]
Replaced with the URI you suggested.
