### ISSUE TITLE
Wrong IE binary

### ISSUE THREAD

**Issue by marcosfrm** [magcius/xplain#30]
Internet Explorer binary is `iexplore.exe`.

https://msdn.microsoft.com/en-us/library/hh826025(v=vs.85).aspx

https://github.com/magcius/xplain/blob/gh-pages/article/x-basics.html#L368

**Comment by zzeroo** [comment]
I think he mean: https://github.com/magcius/xplain/blob/gh-pages/article/x-basics.html#L368

**Comment by magcius** [comment]
Thanks for the report, and the pull request!

**Comment by marcosfrm** [comment]
Still wrong. It is `iexplore.exe`, not `iexplorer.exe`.
