### ISSUE TITLE
composite.html mentions X11 without clarification

### ISSUE THREAD

**Issue by patrakov** [magcius/xplain#37]
https://magcius.github.io/xplain/article/composite.html has this phrase:

"""
I, in perhaps an ill-fated attempt to remain impartial, won't give my opinion on this, specifically, but today I want to talk about another feature commonly seen in modern user interface design, and how it offers challenges with the drawing model *X11* specified and expects clients to use.
"""

However, in https://magcius.github.io/xplain/article/x-basics.html:

"""
If I ever say "such-and-such is a feature of X", it's a bug.
"""

**Comment by magcius** [comment]
Good catch. That should be "The X Window System".
