### ISSUE TITLE
Window inspector has bad XID label

### ISSUE THREAD

**Issue by lilyball** [magcius/xplain#4]
When inspecting a window that has a background-pixmap, a label is added to the top level of the details pane containing the XID. This is added outside of the Attributes or Properties sections, without any label, looking like `<span class="value xid">7</span>`, and it's not removed when selecting a new window. It also has unexpected styling (green italics, left-aligned to the edge of the pane), and since it's not removed, selecting the window multiple times causes it to just keep adding new numbers.

![screen shot 2014-07-11 at 12 40 39 pm](https://cloud.githubusercontent.com/assets/714/3557752/489c19bc-0933-11e4-8f54-c2a6d7f6e60e.png)

The responsible code is at [line 531](https://github.com/magcius/xplain/blob/3e64a2d627251f3aa6b167b502632c7b6d31d010/src/inspector/inspector.js#L531-L535) of inspector.js. I would submit a PR to fix this, but I actually have no idea what the intended behavior here is, so I don't know what to do short of deleting the code. The XID is already visible in the tooltip for the background-pixmap, so I don't know what you were attempting to do by creating this label.

**Comment by magcius** [comment]
Yeah, I have no recollection why it's there, either. I assume it was just leftover debugging code, possibly. Anyway, I just deleted the code.

Thanks!
