### ISSUE TITLE
Add RSS feed to website?

### ISSUE THREAD

**Issue by davidshepherd7** [magcius/xplain#7]
It would be useful to get updates without having to check the site.

[Sorry I can't give you a pull request to go with this, but I don't know how you would go about adding automatic RSS feeds when not using something like Jekyll.]

**Comment by magcius** [comment]
The reason I didn't do this is that the examples have heavy JavaScript, and those obviously won't go through to an RSS reader. If you simply want to know when new articles come out, you can follow my blog at http://blog.mecheye.net . I'll post there every time a new article comes out.

**Comment by davidshepherd7** [comment]
Makes sense, I'll follow the blog instead.
